#!/bin/bash

cd ~/Documents/Repo/cydia
find . -name '*.DS_Store' -type f -delete
find . -name '.deb' -type f -delete
rm -f upload/Packages.gz
rm -rf upload/deb/

cd apps
for SRC in `find . -type d -mindepth 1 -maxdepth 1`
#for SRC in `ls -d */`
do
	dpkg-deb -b -Zgzip ${SRC}
done
mkdir ../upload/deb/
mv *.deb ../upload/deb/
cd ../upload
dpkg-scanpackages -m . /dev/null >Packages
gzip -9 -f Packages
