#!/bin/bash
cd /System/Library/Frameworks/UIKit.framework/

if [[ -f Keyboard-default.plist.bak ]];
then
	cp -f -T Keyboard-default.plist.bak Keyboard-default.plist
fi

if [[ -f Keyboard-en.plist.bak ]];
then
	cp -f -T Keyboard-en.plist.bak Keyboard-en.plist
fi

if [[ -f Keyboard-en_US.plist.bak ]];
then
	cp -f -T Keyboard-en_US.plist.bak Keyboard-en_US.plist
fi

if [[ -f Keyboard-lv.plist.bak ]];
then
	cp -f -T Keyboard-lv.plist.bak Keyboard-lv.plist
fi

echo " "
echo "Respring lūdzu, kthxbye."
echo " "
