#!/bin/bash
function respring {	
	declare -a cydia
	cydia=($CYDIA)

	if [[ ${CYDIA+@} ]]; then
		eval "echo 'finish:restart' >&${cydia[0]}"
	else
		echo "Respring lūdzu."
		killall springboard
	fi
}

function setup_core {
	package=$1
	target="lv.kristapsausters.${package}.core"
	IFS='.' read -ra version <<< "`sw_vers -productVersion`"
	package_dir="/var/root/Library/${package}"
	package_path="`ls ${package_dir}/${target}_${version[0]}*`"
	dpkg -i $package_path
}

setup_core "keyclean"
respring
