#!/bin/bash
function respring {	
	declare -a cydia
	cydia=($CYDIA)

	if [[ ${CYDIA+@} ]]; then
		eval "echo 'finish:restart' >&${cydia[0]}"
	else
		echo "Respring lūdzu."
		killall springboard
	fi
}

respring
