#!/bin/bash
function respring {	
	declare -a cydia
	cydia=($CYDIA)

	if [[ ${CYDIA+@} ]]; then
		eval "echo 'finish:restart' >&${cydia[0]}"
	else
		echo "Respring lūdzu."
		killall springboard
	fi
}

function setup_core {
	target="lv.kristapsausters.keyclean.core"
	IFS='.' read -ra version <<< "`sw_vers -productVersion`"
	package_name="`ls ${target}_${version[0]}*`"
	package_path="../data/${package_name}"
	dpkg -i $package_path
}

setup_core
respring
