#!/bin/bash
cd /System/Library/Frameworks/UIKit.framework/

if [[ -f Keyboard-default.plist.bak ]];
then
	echo ""
else
	mv -f -T Keyboard-default.plist Keyboard-default.plist.bak
fi

if [[ -f Keyboard-en.plist.bak ]];
then
	echo ""
else
	mv -f -T Keyboard-en.plist Keyboard-en.plist.bak
fi

if [[ -f Keyboard-en_US.plist.bak ]];
then
	echo ""
else
	mv -f -T Keyboard-en_US.plist Keyboard-en_US.plist.bak
fi
