#!/bin/bash
cd /System/Library/Frameworks/UIKit.framework/

if [[ -f Keyboard-lv.plist.bak ]];
then
	cp -f -T Keyboard-lv.plist.bak Keyboard-lv.plist
fi

echo " "
echo "Respring lūdzu, kthxbye."
echo " "
